version: '3'

services:
  # The reverse proxy service (Traefik)
  reverse-proxy:
    image: traefik  # The official Traefik docker image
    # command: --api --docker  # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "8081:8081"      # The HTTP port
      - "8090:8090"  # The Web UI with an overriden port
      - "9145:9145"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # So that Traefik can listen to the Docker events
      - $PWD/traefik.toml:/etc/traefik/traefik.toml

  # A container that exposes a simple API
  nginx:
    image: nginx  # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=Path: /"
  httpd:
    image: httpd  # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=PathPrefixStrip: /httpd"
  sandwiches:
    image: ollyjshaw/sandwiches  # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=PathPrefixStrip: /ruby"

