[api]

[docker]

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"
    buckets = [0.005,0.01,0.02,0.03,0.05,0.075,0.1,0.2,0.3,0.4,0.5,0.75,1.0,1.5,2.0,3.0,4.0,5.0,10.00]

[entryPoints]
  [entryPoints.http]
    address = ":8081"
  [entryPoints.api]
    address = ":8090"
  [entryPoints.metrics]
    address = ":9145"